### ISSUE TITLE
PHP 7 Compatibility

### ISSUE THREAD

**Issue by pcr-coding** [exploreimpact/contao-i18nl10n#100]
Mit PHP 7 gibt's Probleme mit der `String` Klasse, da diese [nicht mehr `String` heißen darf](http://php.net/manual/en/migration70.incompatible.php#migration70.incompatible.other.classes). Stattdessen sollte die mit Contao 3.5.1 eingeführte Klasse `StringUtil` verwendet werden.

Ersetzen von `String::` durch `StringUtil::` hat mir erst mal geholfen. Andere Inkombatibilitäten mit PHP 7 hab ich bis jetzt nicht entdeckt.

**Comment by internetinnovations** [comment]
We will fix this issue for the next release.
