### ISSUE TITLE
<link rel="alternate" wird nicht korrekt erzeugt

### ISSUE THREAD

**Issue by pcr-coding** [exploreimpact/contao-i18nl10n#101]
Bei mir wird der 

```
<link rel="alternate" href="/en/myEnglishSite.html" hreflang="en" title="MyTitle" />
```

 nicht korrekt erzeugt. Stattdessen bekomme ich 

```
<link rel="alternate" href="/en/.html" hreflang="en" title="MyTitle" />`
```

Kann das jemand bestätigen?

Als Fehlerquelle konnte ich die Funktion [`addAlternativeLanguageLinks()`](https://github.com/verstaerker/i18nl10n/blob/master/src/system/modules/i18nl10n/pages/PageI18nl10nRegular.php#L137) ausmachen. Wenn ich `$page['id'] = $objPage->id;` direkt hinter `$page['forceRowLanguage'] = true;` einfüge wird der Link richtig erzeugt.

**Comment by danielroeding** [comment]
Ja selber Fehler bei unseren Seiten. 
Danke @pcr-coding für den Fix. Werde ich gleich testen.

Update: Auf der DE Version stimmt nun der href zur EN Version. Nur umgekehrt noch nicht.

**Comment by rolandschuetz** [comment]
Ich kann den Fehler, und die teilweise Lösung bestätigen.

**Comment by Webstylerin** [comment]
Ich ebenso. Fehler ist auch bei mir vorhanden und Lösung funktionert bis auf den Link auf die Standard-Sprache.

Zudem fehlt bei mir die Selbstreferenzierung der aktuellen Seite.

**Comment by Floxn** [comment]
Ich kann genauso beide Bestätigen. 
Kombiniert man aber den oben genannten Fix mit dem von [baumannsven](https://github.com/baumannsven): https://github.com/internetinnovations/i18nl10n/pull/107/commits/551ef68ae5b824de519f9205949681ebb6c61622
erhält man das passende Ergebnis.

/* 2017-08: Updated Link

**Comment by rolandschuetz** [comment]
Svens fix löst alle Probleme.

**Comment by Webstylerin** [comment]
Wenn ich Svens Fix einfüge bekomme ich zwar Verlinkungen für alle Fremdsprachen, aber die Verlinkungen sind falsch. Es werden komplett andere Seiten verlinkt.

Wenn ich aber die Zeile von pcr-coding aus dem ersten Post mit einfüge, stimmen die Links.

Es fehlt aber immer noch die Selbtsverlinkung der aktuellen Seite.

**Comment by rolandschuetz** [comment]
Vielleicht kann @verstaerker hier ja helfen...

**Comment by danielroeding** [comment]
Danke Leute 👍  
Der FIX von Sven + pcr-coding funktionieren.
Zur "Selbstverlinkung" kann ich nix sagen. Braucht man das?

**Comment by Webstylerin** [comment]
Laut Google braucht man die Selbstverlinkung: "... auch einen rel="alternate" hreflang="x"-Link für sich selbst enthalten."
Quelle: https://support.google.com/webmasters/answer/189077?hl=de

**Comment by Webstylerin** [comment]
Habe (dank Hanski) eine Lösung für die fehlende Selbstreferenzierung.

Dazu in der Datei classes/I18nl10n.php in Zeile 497 aus der Funktion folgendes löschen:
- "AND language != ?" (2x)
- ", $objPage->language" (2x)

Das sieht dann so bei mir aus:

        return \Database::getInstance()
            ->prepare("
                SELECT $fields
                FROM tl_page_i18nl10n
                WHERE pid = ? AND i18nl10n_published = 1
                UNION
                SELECT $fields
                FROM tl_page
                WHERE id = ? AND i18nl10n_published = 1
            ")
            ->execute($objPage->id, $objPage->id)
            ->fetchAllAssoc();

**Comment by internetinnovations** [comment]
This task has a high priority and will be fixed in the next release.

**Comment by paulhaem** [comment]
Die Fixes sind nicht mehr verfügbar. Wär für eine Zwischenlösung ganz gut, wenn sie in diesem Repo nochmal festgehalten werden würden. Danke im Voraus!

**Comment by paulhaem** [comment]
@Floxn könntest du vielleicht den Fix von Sven zur Verfügung stellen?

**Comment by Floxn** [comment]
@paulhaem das hier müssten sie sein: https://github.com/internetinnovations/i18nl10n/pull/107/commits/551ef68ae5b824de519f9205949681ebb6c61622

**Comment by paulhaem** [comment]
Ich bin grad auch zufällig drauf gestoßen. Vielen Dank!

**Comment by paulhaem** [comment]
Die Fixes haben soweit ganz gut funktioniert, jedoch ist mir aufgefallen, dass wenn sich die Website in einem Unterordner befindet, die Links wieder nicht richtig generiert werden.

Aus `href="/en/.html"` wurde `href="/en/about.html"`, jedoch fehlte `/subfolder`, sodass das `href` auch richtig weiterleitet. Weil so führt die Verlinkung zu `www.domain.com/en/about.html` (404) anstelle von `www.domain.com/subfolder/en/about.html`. Die Base-URL sieht folgendermaßen aus: `<base href="www.domain.com/subfolder/">`

EDIT: Ich konnte mit einem dirty Hack das fürs erste fixen, indem ich bei `$links[]` den Unterordner fix mitgebe.

**Comment by Aybee** [comment]
Ich benutze Version 1.5.5 in Contao 3.5. Dort funktioniert es bei mir nur mit dem Code von @Webstylerin https://github.com/exploreimpact/contao-i18nl10n/issues/101#issuecomment-272827893

Zusätzlich die Anpassungen von @baumansven. Und das `$page['id'] = $objPage->id;` von @pcr-coding 

Ohne den Code von @Webstylerin sind die Links weiterhin `/en/.html` bzw. `/de/.html`

Wie man sieht benutze ich die Option `als Teil der URL (z.B. mypage.com/en/index.html)`. Folder-URLs habe ich nicht.

Könnte man diese Anpassungen bitte in die Version 1.5.5(6) übernehmen?

**Comment by Aybee** [comment]
IMHO müsste hier auch das erste Slash weg, da das base-Element ja immer bereits mit nem Slash endet.
https://github.com/exploreimpact/contao-i18nl10n/blob/master/src/Resources/contao/pages/PageI18nl10nRegular.php#L187
```php
                - . "href=\"/{$strUrl}\" "
                + . "href=\"{$strUrl}\" "
```

**Comment by Aybee** [comment]
> @pcr-coding Wenn ich $page['id'] = $objPage->id; ... einfüge wird der Link richtig erzeugt.

Zur Info: Die Funktion `\Controller::generateFrontendUrl($page);` https://github.com/exploreimpact/contao-i18nl10n/blob/master/src/Resources/contao/pages/PageI18nl10nRegular.php#L184 bekommt ein Array aus welchem sie die URLs erzeugen soll. Beispiel:
```
Array
(
  [0] => Array
    (
      [title] => Team EN
      [language] => en
      [id] => 106
      [pid] => 123
      [alias] => team-en
      [i18nl10n_published] => 1
    )
  [1] => Array
    (
      [title] => Team DE
      [language] => de
      [id] => 123
      [pid] => 3
      [alias] => team-de
      [i18nl10n_published] => 1
    )
)
```
In obigem Beispiel liegt die Seite mit der ID **106** aber nicht in tl_page, sondern in tl_page_i18nl10n. `generateFrontendUrl` generiert somit eine URL aus tl_page mit der ID **106** was falsch ist. Überschreibt man jetzt die id `$page['id'] = $objPage->id[123]`, dann scheint es zu funktionieren.
