### ISSUE TITLE
Wrong Domain in Sitemap (Multi-Domain-Installation)

### ISSUE THREAD

**Issue by comede** [exploreimpact/contao-i18nl10n#102]
When generating the sitemap (automtically or via backend) always the domain under which the generation is executed is shown in the sitemap. The DNS-Entry in the Website root is ignored. When i comment out the hook:

``` php
//  $GLOBALS['TL_HOOKS']['generateFrontendUrl'][] = array($strClassName, 'generateFrontendUrl');
```

in the i18nl10n-config the domain in the sitemap is ok but the the language-folder-prefixes are missing.

if fixed this temporarily in I18nl10nHook.php::generateFrontendUrl

``` php
// 2016-05-09 come medien ag
// Add the domain if present in function-param "$strUrl"
$preventDomainPrefix = preg_match("/^((https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})\/).*$/", $strUrl, $matches);
$domainPrefix = ($preventDomainPrefix) ? $matches[1] : '';
(...)
return $domainPrefix . $strL10nUrl;
```

**Comment by internetinnovations** [comment]
Most probably we will integrate our new sitemap extension into the i18nl10n. That might also solve this sitemap issue.
