### ISSUE TITLE
<select> with IE not working

### ISSUE THREAD

**Issue by patric-eberle** [exploreimpact/contao-i18nl10n#103]
ich denke ich habe einen Fehler bei der Umstellung der Sprachen im Internetexplorer gefunden.

Diese betrifft nur das select-Menü.

Beim IE wird wird bei mehrfachem Umstellen der Sprache, bei der Contao Einstellung Urls umschreiben -> als Teil der URL (z.B. mypage.com/en/index.html), jeweils immer die Sprache zusätzlich vor der jeweiligen Seite angezeigt. Diese konkateniert pro Wechsel immer weiter.

Z.B:
1. Aufruf der Seite: mypage.com
2. Aufruf mit Sprachenwechsel mypage.com/de/…
3. Aufruf der gleichen Seite mit select-Feld ->  mypage.com/de/en/… usw.

Meine .htaccess Dateien habe ich schon mehrfach verändert und überprüft und es funktionierte vorher auch sowohl in allen Browsern als auch mit dem lang-default Template. Damit geht es auch beim IE reibungslos.

**Comment by internetinnovations** [comment]
Needs to be reproduced and tested.
