### ISSUE TITLE
Sitemap.xml i18nl10n News

### ISSUE THREAD

**Issue by MrLumbergh** [exploreimpact/contao-i18nl10n#108]
I have installed i18nl10n with german as standard and english as another language.
I have news-archives for de and en.

The news archives are correctly displayed with
`https://www.customer.de/en/news-detail/join-us-for-the-webcast.html`

In the sitemap.xml it's wrong like this:
`https://www.customer.de/de/news-detail/join-us-for-the-webcast.html`

Can I do something to fix it?

**Comment by internetinnovations** [comment]
Most probably we will integrate our new sitemap extension into the i18nl10n. That might also solve this News sitemap issue.
