### ISSUE TITLE
French (Belgium) and German (Belgium) missing as languages

### ISSUE THREAD

**Issue by internetinnovations** [exploreimpact/contao-i18nl10n#110]
- deleted

**Comment by internetinnovations** [comment]
This is a Contao Core issue (wrong project for this ticket)

**Comment by christianromeni** [comment]
So, you have taken over the project?

**Comment by internetinnovations** [comment]
@christianromeni 
Yes, we are in transition. More details (german):
https://community.contao.org/de/showthread.php?48943-i18nl10n-Neuer-Entwickler-gefunden&p=434393&viewfull=1#post434393
