### ISSUE TITLE
Flag and lang codes not linked correct

### ISSUE THREAD

**Issue by qbadev** [exploreimpact/contao-i18nl10n#111]
Contao 3.5, i18nl10n 1.5.5
I have found out that Swedish lang is mapped to sv.png flag, which is Salvador flag. There is an approach problem, as languages codes do not map well with country codes which are used as flag names. 
Sweden language code in Contao is SV which is Salvadore country code.

In the future also Contao core (below version 4) should be updated with list of full lang codes with country suffix (i.e. sv_SE for swedish). Then i18nl10n should list only langs with country suffix.

**Comment by matthiasprieth** [comment]
[related to this issue](https://github.com/internetinnovations/i18nl10n/issues/114)
