### ISSUE TITLE
i18nl10n - Events / contao 3.5.

### ISSUE THREAD

**Issue by TildaSchmitt** [exploreimpact/contao-i18nl10n#117]
Hallo,

ich arbeite unter contao 3.5. und habe das Problem, dass Events nicht zweisprachig angelegt werden können.
Ist das Problem mittlerweile behoben?
Beste Grüße
Tilda

**Comment by Aybee** [comment]
She asks if version 2.x meanwhile supports events. She is using the latest version 1.5.5 from ER2 within Contao 3.5.35.

If so we like to do a manual update to the latest version 2.x.

**Comment by ClaudioDeFacci** [comment]
Sorry for the late response. Had no time to answer during my holidays.
Events (and News) are still not supported. But there are several people asking for this feature, so I will try to implement it within the next 3 months. It's just a question of time.

**Comment by Aybee** [comment]
So far I removed the unsupported modules and this seams to work for me
https://github.com/exploreimpact/contao-i18nl10n/blob/master/src/Classes/I18nl10n.php#L31
```php
protected $unsupportedModules = array('news');
```
News are not active in this installation so I only tested the calendar so far.
