### ISSUE TITLE
Only back end language is visible in BE preview

### ISSUE THREAD

**Issue by Aybee** [exploreimpact/contao-i18nl10n#118]
What am I missing? What do I have to do so I will see all languages in BE previews and not only my own BE language?

**Comment by Aybee** [comment]
So far I patched this HOOK https://github.com/exploreimpact/contao-i18nl10n/blob/1.5.5/src/system/modules/i18nl10n/classes/I18nl10nHook.php#L240 with
```php
    public function isVisibleElement($objElement, $blnIsVisible)
    {
      if(TL_MODE == 'BE')
      {
        return true;
      }
        global $objPage;
...
```

**Comment by ClaudioDeFacci** [comment]
I will implement the fix asap within the next two weeks.
