### ISSUE TITLE
Umleitungsfehler auf Startseite ?language=de

### ISSUE THREAD

**Issue by erikherbert** [exploreimpact/contao-i18nl10n#120]
http://test480.hostingwerk.rocks

Unterseiten werden nicht geladen bzw. falsch umgeleitet.

**Comment by zladdi2018** [comment]
Habe das gleiche Problem, sobald Submenüs da sind funktionieren diese nur in der deutschen sprache und mit der option language=de, die anderen Varianten gehen nicht. Bei der englischen sprache funktionieren die Submenüs gar nicht.

**Comment by ClaudioDeFacci** [comment]
Ich werde versuchen im September eine Runde über die Extension zu drehen und mir in dem Rahmen das Problem anzuschauen.
