### ISSUE TITLE
Fehler im Bildpfad für Neutrale Sprache

### ISSUE THREAD

**Issue by zladdi2018** [exploreimpact/contao-i18nl10n#121]
Die Verlinkung ist falsch.

Richtig wäre einmal in der tl_article.php und in der tl_page.php im dca Ordner...

tl_article.php: Zeile 71
`
               $l10nItemIcon   = 'bundles/verstaerkeri18nl10n/img/i18nl10n.png';
`

tl_page.php: Zeile 179

`'<a href="%1$s" title="%2$s"><img src="bundles/verstaerkeri18nl10n/img/%3$s"></a>',`

Aktuell steht die alte Verlinkung mit **system/module/....**
Danach Cache über Contao-Manager löschen damit das Ergebniss zu sehen ist.

Verwendete Version
Contao 4.4.20
i18nl10n 2.0.0-beta2

**Comment by ClaudioDeFacci** [comment]
Danke für den Hinweis. Wird im nächsten Release berücksichtigt!
