### ISSUE TITLE
after installation the Symfony Debug Toolbar no longer works

### ISSUE THREAD

**Issue by zonky2** [exploreimpact/contao-i18nl10n#124]
after installation `exploreimpact/contao-i18nl10n:2.0.0-beta` the Symfony Debug Toolbar no longer works

maybe in relation with https://github.com/exploreimpact/contao-i18nl10n/issues/123

**Comment by zonky2** [comment]
why closed? fixed?

**Comment by exploreimpact** [comment]
Could not replicate this problem locally. It's most probably fixed in dev-master. Will be included in the next release.
