### ISSUE TITLE
Related content elements

### ISSUE THREAD

**Issue by verstaerker** [exploreimpact/contao-i18nl10n#19]
Check if it's possible to create and display related content elements.

This could be done by a l10nPid which targets the original content element. Sub elements could be created by a special button on the element or linked afterwards by a helper.

How could related elements be shown in edit mode?

**Comment by christianromeni** [comment]
This sounds like an awesome feature to add mode usability! :+1:

**Comment by internetinnovations** [comment]
This is a bigger issue and cannot be solved easily. Task will not be realized in the next version.
