### ISSUE TITLE
Improve search integration

### ISSUE THREAD

**Issue by patric-eberle** [exploreimpact/contao-i18nl10n#40]
The search funciton of Contao seems not to work well with i18nl10n.
- [x] Index localized pages and content
- [x] Only show localized content when searching in FE

**Comment by christianromeni** [comment]
Should this be working? How can I configure this..
I'm on the German page, and getting english results as well:

Search for "News"
Getting:
http://domain.de/de/news.html
http://domain.de/en/news.html

Greets - Chris

**Comment by patric-eberle** [comment]
Did you follow the wiki instructions? Are you using Contao 3.3+? Did you re-index your pages after the module installation?

**Comment by christianromeni** [comment]
Yes, I have installed it the way it is supposed to be.
I'm on Contao 3.4
I re-indexed the pages today afternoon, the modules has been on ht esystem for months..

**Comment by patric-eberle** [comment]
Made a short test with 3.4 on my system. Seems to work as expected. Did you use 'AND' or 'OR' search? Unfortunately the 'OR' search can not be filtered correctly without messing up the results.

**Comment by christianromeni** [comment]
Ok, this might be the Problem.. I'm using OR... ThenI guess I'll have to Filter the results using JavaScript as a workaround...

Thanks for the feedback.
