### ISSUE TITLE
Content elements in custom module

### ISSUE THREAD

**Issue by christianromeni** [exploreimpact/contao-i18nl10n#45]
I have created a module, that uses the content elements as described here:
https://contao.org/de/cookbook/3.0/inhaltselemente-verwenden.html

Since they are regular content elements, I would expect them to have the language settings:
L10N Einstellungen.

But they dont... why is that so, and can it be fixed easily? So that I can maybe do it myself till you find the time to add it to a new version?

**Comment by patric-eberle** [comment]
This is due the fact, that the current condition for the dca modification is bound to the article module, since the news module is not supported. I will change the condition to a negative one, so the tl_content dca will be modified always except for the news module.

**Comment by patric-eberle** [comment]
@christianromeni could you please test the change with the latest version of the develop branch? https://github.com/verstaerker/i18nl10n/tree/develop

**Comment by christianromeni** [comment]
Is it possible via composer? If yes.. how.. I have never installed from git itself..

**Comment by patric-eberle** [comment]
Sorry. No, you would need to download the 'zip' in the right lower column. Than replace the i18nl10n folder in your contao/system/modules folder with the one in the zip file. In the modules view you should run 'update databases'. Be aware, that the module information in the Contao BE will still show the last installed module version.

**Comment by christianromeni** [comment]
I think the one one the right will only download the master..? But I will clone and switch to dev..

**Comment by christianromeni** [comment]
Warning: explode() expects parameter 2 to be string, array given in system/modules/core/library/Contao/String.php on line 652
0 [internal function]: __error(2, 'explode() expec...', '/home/php-deplo...', 652, Array)
1 system/modules/core/library/Contao/String.php(652): explode('|', Array)
2 system/modules/core/classes/BackendTemplate.php(80): Contao\String::resolveFlaggedUrl(Array)
3 system/modules/core/controllers/BackendMain.php(268): Contao\BackendTemplate->output()
4 system/modules/core/controllers/BackendMain.php(130): Contao\BackendMain->output()
5 contao/main.php(20): Contao\BackendMain->run()
6 {main}

**Comment by patric-eberle** [comment]
Yeaii. Sorry, not able to take a look at the issue right now. will let you know if I know more.... Sorry for the inconvenience. You should be able to repair the module by reinstalling via backend module.
