### ISSUE TITLE
i18nl10n  does not work with Isotope

### ISSUE THREAD

**Issue by tsarma** [exploreimpact/contao-i18nl10n#46]
Contao 3.4.3
i18nl10n    1.3.0
Isotope 2.2.2

After installing your module, Isotope drop down language menu disappears. Is there any work around?

**Comment by patric-eberle** [comment]
Is this an issue in front or back end?

**Comment by patric-eberle** [comment]
Found the problem. There is module related code inside the Isotope module, which is no longer supported. Will create a pull request and deliver a required method for Isotope.

**Comment by patric-eberle** [comment]
Release 1.3.1 will have a workaround to allow usage with Isotope until a callback solution is integrated in Isotope.

**Comment by tsarma** [comment]
With i18nl10n release 1.3.2, the problem (Isotope drop down language menu disappears) is solved. Thank you
