### ISSUE TITLE
Native support for Contao-Composer Package-Manager

### ISSUE THREAD

**Issue by dtomasi** [exploreimpact/contao-i18nl10n#60]
We use this extension in a project where we had to make some changes. To have the ability to receive bugfixes we created a fork and used a special branch for this.
For this we needed to include the native support for Contao´s Composer Package-Manager which is included in a separated feature-branch. If you like to include it pleas let me know.

see: https://github.com/upcom-ch/i18nl10n/commits/feature/composer

Best regards
Dominik Tomasi

**Comment by patric-eberle** [comment]
Thank you for letting me know about your work. Since composer is a must have in the future, I would relay like to user your implementation as a base.

Regards
Patric

**Comment by dtomasi** [comment]
@patric-eberle My pleasure. Would you like to have a PR for this?

**Comment by patric-eberle** [comment]
@dtomasi This would be helpful. Thank you.
