### ISSUE TITLE
Sucheergebnisse funktionieren nur für eine Sprache

### ISSUE THREAD

**Issue by jankout** [exploreimpact/contao-i18nl10n#64]
Hallo, 

leider funktionieren die Suchergebnisse nur für eine Sprache - siehe auch hier https://community.contao.org/de/showthread.php?56824-i18nl10n-Suche-liefert-quot-komische-quot-Ergebnisse

Bei mir geht es nur für die Sprachvariante, für die das Redaktionssystem die Suchindex erstellen konnte. Kann man wirklich mit dieser Erweiterung alles indexieren lassen, damit die Suche funktioniert? Oder muss man im Quellcode des Suchmoduls etwas anpassen? 

Liebe Grüße,

Jan

https://community.contao.org/de/showthread.php?48943-i18nl10n-Neuer-Entwickler-gefunden/page5&p=369662#post369662

**Comment by patric-eberle** [comment]
Search module was not configured as described in wiki.
