### ISSUE TITLE
Improve search support

### ISSUE THREAD

**Issue by patric-eberle** [exploreimpact/contao-i18nl10n#65]
Search support is still not satisfying and the users stumble when setting it up.
- [ ] Improve search result quality
- [ ] Improve implementation
- [ ] Improve setup
- [ ] News items are not correctly indexed

**Comment by patric-eberle** [comment]
Support for news items is currently not possible, since its not possible to determine the language of an entry. Possibly this could be fixed by adding a language definition to tl_news_archive?

**Comment by patric-eberle** [comment]
... or even better by adding language definition to tl_news

**Comment by jankout** [comment]
And, please, it would be very useful to improve the search index. When I let build it the search index contents the news or event entries from another languages too and it sets the wrong language before (e.g. en).

**Comment by jankout** [comment]
How does it look with this feature? I think it´s very important for SEO.

**Comment by internetinnovations** [comment]
Search function compatibility needs to be refactored in general. This will not be realized in the next version.
