### ISSUE TITLE
Inserttag {{page::parentTitle}} nimmt nur die Hauptsprache

### ISSUE THREAD

**Issue by jankout** [exploreimpact/contao-i18nl10n#67]
Lieber Patric, 

heute kam ich darauf, dass das Inserttag {{page::parentTitle}} nur den Seitentitel der Hauptsprache ausgibt. Kann ich es irgendwie selbst beseitigen? 

Unten findest du meine Einstellung bei dem Navigationsmodul.

Liebe Grüße,
Jan
![bildschirmfoto 2015-06-09 um 18 00 18](https://cloud.githubusercontent.com/assets/3715050/8062726/834d74f8-0ed1-11e5-96cb-b4f246500adf.png)

**Comment by patric-eberle** [comment]
Hallo Jan

Auf die Schnelle habe ich dir leider keine Lösung. Muss mir mal ansehen wie sich dieser Inserttag die Informationen besorgt. Ev. kann ich mich in einen Hook einhängen oder muss einen eigenen Inserttag erstellen.

Gruss
Patric

**Comment by jankout** [comment]
Das wäre natürlich klasse. :+1: Ich danke dir für deine tolle Arbeit. 

Sonst habe ich noch gedacht, dass es noch nützlich wäre, wenn man auch bei den einzelnen Formularelementen die Sprachvariante auswählen könnte. Hoffentlich ist es OK, wenn ich immer wieder mit neuen Vorschlägen komme. :-)
