### ISSUE TITLE
Correct switching between news and events

### ISSUE THREAD

**Issue by jankout** [exploreimpact/contao-i18nl10n#69]
Currently the switching between the news and event is not correct - it is being showed an article without any news content (article.html). Maybe it would be better to set the link to the parent page with the news list or find a solution like by the extension newslanguage https://contao.org/de/extension-list/view/newslanguage.10000029.de.html 

What do you think?

**Comment by jankout** [comment]
Hallo Patric, wie sieht es mit dieser tollen Funktion aus? Ich hoffe, dass du erholt und voller tollen Erlebnisse von deiner Wanderung zurückgekommen bist.

**Comment by internetinnovations** [comment]
We have solved this by developing own extensions. Maybe we will refactor these as separated modules i18nl10n-news and i18nl10n-events. This will not happen with the next release.
