### ISSUE TITLE
Article Teasers translatable?

### ISSUE THREAD

**Issue by pcr-coding** [exploreimpact/contao-i18nl10n#71]
Is there a way to translate the title and the teaser of an article? Or is this function missing yet?

**Comment by patric-eberle** [comment]
This option is not existing yet. please use a separate news archive.

**Comment by squidi** [comment]
Für das Newsarchiv mag das eine Alternative sein, für die Article-Teaser funktioniert das allerdings nicht. Da wäre eine Mehrsprachigkeit schon wichtig für die Headline und das Textfeld. Vielleicht in Verbindung mit 'multicolumnwizard'

**Comment by jankout** [comment]
:+1: That would be fine.

**Comment by internetinnovations** [comment]
This feature has a low priority and will not be solved with the next release.
