### ISSUE TITLE
Webseite unter Android 4.4.2. nicht sichtbar

### ISSUE THREAD

**Issue by matuweb** [exploreimpact/contao-i18nl10n#77]
Ich habe die Erweiterung (Version 1.5.2) in Contao 3.4.5 eingebaut und die Seite dreisprachig aufgebaut.
Jetzt habe ich festgestellt, dass die Seite nicht auf dem Smartphone mit dem Betriebssystem Android 4.4.2 läuft. Wohl aber auf den Systemen 4.2.2 und 4.3.
Der Bildschirm bleibt weiß. Deaktiviere ich das Modul, erscheint die Seite normal.

**Comment by patric-eberle** [comment]
Hast du mir einen Tipp, wie ich das Testen könnte? Ich besitze kein entsprechendes Gerät. Eclipse?

**Comment by patric-eberle** [comment]
Ich habe versucht den Bug jetzt mit einem virtuellen Android Installation nachzustellen. Hatte aber kein Erfolg. Bist du sicher, dass das Problem durch das Modul selber verursacht wird? Oder gibt es ev. noch einen Modulkonflikt mit anderen Modulen?

**Comment by matuweb** [comment]
Also ich kann nur so viel sagen, dass als ich das Modul deaktiviert hatte, lief die Seite normal unter der angegebenen Android-Version.

Somit kann ich nichts über evtl. andere Module/Scripte sagen, sorry.

Viele Grüße
Christian

Am 12.09.2015 um 19:23 schrieb Patric Eberle notifications@github.com:

**Comment by internetinnovations** [comment]
We have not been able to reproduce this issue. Ticket will be closed.
