### ISSUE TITLE
Page Title in Insert Tags is Not Translated

### ISSUE THREAD

**Issue by pcr-coding** [exploreimpact/contao-i18nl10n#87]
If you use an insert tag like `{{link::127}}` to link to another page it is not translated.

As I didn't find any insert tag replacement in the code of i18nl10n this might be an issue to other tags beside the link tag too.

//Edit
I checked this and there seems to be no method to overwrite a core insert tag. The only way would be to create a new insert tag like `{{link_i18nl10n::127}}`. Because all insert tags are handled in one core function overwriting the controller function is also no option. If there was one function each tag this would be much easier to handle.

**Comment by patric-eberle** [comment]
True. This is due the fact that only navigation elements are translated if one of the module templates is selected. I'm not sure if it would be a good idea to change this globally. An additional inserttag is probably the most flexible way, but I'd like to keep them to a minimum.

**Comment by kartoffelheinz** [comment]
I would need this functionality as well, we currently cannot use sub_navigations having the parent page title as headline. Any news on how long it will take to implement this?

**Comment by patric-eberle** [comment]
I will try to fix this issue until next week.

**Comment by patric-eberle** [comment]
With version 1.5.5 you can use the inserttag {{i18nl10n::link::#}} to create a localized link.

**Comment by pcr-coding** [comment]
Nice thats what I was looking for, but is this only working with ids? The core `{{link::#}}` also works with aliases I think. I just came across this after replacing all `{{link::#}}` with `{{i18nl10n::link::#}}`.
