### ISSUE TITLE
1.5.4 Fehlende Länderfahnen und Sprachen im Auswahlmenü

### ISSUE THREAD

**Issue by jankout** [exploreimpact/contao-i18nl10n#88]
Hallo, 

seit der Aktualisierung 1.5.4 fehlen die Länderfahnen bei den Inhaltselementen in Inhaltsboxen (box4ward) und Rocksolid Slider. Außerdem kann man da die Sprachen nicht auswählen bzw. es gibt nur Neutral zur Auswahl. 

Könntest du bite diesen Fehler beseitigen? Vielen Dank. 

Liebe Grüße,
Jan 

Siehe auch https://community.contao.org/de/showthread.php?48943-i18nl10n-Neuer-Entwickler-gefunden/page6&p=384159&viewfull=1#post384159

![bildschirmfoto 2015-09-15 um 14 45 05](https://cloud.githubusercontent.com/assets/3715050/9876785/ea726484-5bb8-11e5-83ef-314578cb5baf.png)
![bildschirmfoto 2015-09-15 um 14 46 16](https://cloud.githubusercontent.com/assets/3715050/9876788/eef39d34-5bb8-11e5-8780-001301183755.png)

**Comment by patric-eberle** [comment]
Also war in der letzten Version noch alles ok?

**Comment by jankout** [comment]
Eigentlich ist es dort auch schon gesponnen (eingeschränkte Sprachenauswahl). Nur die Flaggen konnte man sehen.

**Comment by pcr-coding** [comment]
Ich bin mir nicht ganz sicher, ob es sich um den gleichen Fehler handelt, aber bei mir kommt es auch ab und an vor, dass ich nur `Neutral` zur Auswahl hab.

Meines Erachtens liegt der Hund in der Funktion `getLanguageOptionsByContentId` in `tl_contont.php` begraben und zwar in der SQL-Abfrage gleich am Anfang. Hier wird nämlich die `pid` aus der `tl_content` geholt und ungeachtet dessen, was dort in der Spalte `ptable` eingetragen ist einfach angenonmmen, dass es sich um einen Artikel (aus `tl_article`) handelt. Jetzt könnte aber auch die `pid` eine News (aus `tl_news`) sein oder was es noch spannender macht wie in meinem Fall ein selbst programmierter Typ sein. Der Fehler fällt erst mal nicht auf solange ein Artikel mit der `pid` existiert. Ist das aber nicht der Fall, so bleibt nur noch die Auswahl `Neutral` übrig.

Eine Lösung ist mir leider nicht eingefallen, aber die SQL-Abfrage ist so auf alle Fälle nicht richtig. Die Abfrage statt auf die `tl_article` einfach auf die jeweilige Tabelle aus `tl_content.ptable` zu schicken funktioniert nämlich nur bedingt, da in meinem Fall eine `pid` dort nicht vorhanden ist, da ich dafür eine extra Tabelle habe in der eine Zuordnung auf mehrere `pids` möglich ist. Zumindest müsste dann hier gleich noch ein hook mit rein so dass man die funktion für eigene Content-Typen gleich ergänzen kann.

**Comment by patric-eberle** [comment]
Das Hinzufügen eines Hooks wird etwas mehr Zeit benötigen, da ich erst klären muss, wo dieser am sinnvollsten einzusetzen ist. Ich habe dafür ein neues Ticket erstellt (#89). Um anderen Modulen trotzdem bereits die Möglichkeit zu bieten, Sprachen zu verwenden, wird die Sprachwahl neu in Dritt-Modulen mit allen für den aktuellen Benutzer verfügbaren Sprachen angezeigt. Eine Unterscheidung nach Domain ist an dieser Stellle allerdings nicht möglich.

**Comment by jankout** [comment]
Danke, Patric. Was meinst du genau damit, dass dies nicht nach der Sprachvariabel in der Domain umgeschaltet wird? Wenn ich es richtig verstehe, würde es dann nicht standardmäßig funktionieren?

Jan Kout

---

DE: +49 176 45799488
CZ: +420 728 781 067

www.jankout.eu
koutjan@gmail.com
1. 9. 2015 v 16:10, Patric Eberle notifications@github.com:

Das Hinzufügen eines Hooks wird etwas mehr Zeit benötigen, da ich erst klären muss, wo dieser am sinnvollsten einzusetzen ist. Ich habe dafür ein neues Ticket erstellt (#89). Um anderen Modulen trotzdem bereits die Möglichkeit zu bieten, Sprachen zu verwenden, wird die Sprachwahl neu in Dritt-Modulen mit allen für den aktuellen Benutzer verfügbaren Sprachen angezeigt. Eine Unterscheidung nach Domain ist an dieser Stellle allerdings nicht möglich.

**Comment by pcr-coding** [comment]
@jenda77 so wie ich das verstanden hab ist es jetzt so, dass für alle contents vom parent typ `tl_article` in der Sprachauswahlbox nur die Sprachen angezeigt werden die für diese Domain eingestellt wurden. Für alle anderen Module die nicht in `tl_article` sind werden einfach alle Sprachen angezeigt die für den aktuelle Benutzer eingestellt sind (quasi als workaround bis das mit dem Hook funktioniert).

**Comment by patric-eberle** [comment]
@pcr-coding genau ;)
