### ISSUE TITLE
Add hook to change available languages

### ISSUE THREAD

**Issue by patric-eberle** [exploreimpact/contao-i18nl10n#89]
Add a hook for 3rd party modules to allow the modification of available languages for a BE user.

**Comment by patric-eberle** [comment]
Comment from #88:

Ich bin mir nicht ganz sicher, ob es sich um den gleichen Fehler handelt, aber bei mir kommt es auch ab und an vor, dass ich nur Neutral zur Auswahl hab.

Meines Erachtens liegt der Hund in der Funktion getLanguageOptionsByContentId in tl_contont.php begraben und zwar in der SQL-Abfrage gleich am Anfang. Hier wird nämlich die pid aus der tl_content geholt und ungeachtet dessen, was dort in der Spalte ptable eingetragen ist einfach angenonmmen, dass es sich um einen Artikel (aus tl_article) handelt. Jetzt könnte aber auch die pid eine News (aus tl_news) sein oder was es noch spannender macht wie in meinem Fall ein selbst programmierter Typ sein. Der Fehler fällt erst mal nicht auf solange ein Artikel mit der pid existiert. Ist das aber nicht der Fall, so bleibt nur noch die Auswahl Neutral übrig.

Eine Lösung ist mir leider nicht eingefallen, aber die SQL-Abfrage ist so auf alle Fälle nicht richtig. Die Abfrage statt auf die tl_article einfach auf die jeweilige Tabelle aus tl_content.ptable zu schicken funktioniert nämlich nur bedingt, da in meinem Fall eine pid dort nicht vorhanden ist, da ich dafür eine extra Tabelle habe in der eine Zuordnung auf mehrere pids möglich ist. Zumindest müsste dann hier gleich noch ein hook mit rein so dass man die funktion für eigene Content-Typen gleich ergänzen kann.

**Comment by patric-eberle** [comment]
@myself: Ev. gemäss Isotope lösen.

**Comment by jankout** [comment]
Danke, Patric. Was meinst du genau damit, dass dies nicht nach der Sprachvariabel in der Domain umgeschaltet wird, wie du es im alten Ticket kommentiert hast? Wenn ich es richtig verstehe, würde es dann nicht standardmäßig funktionieren?

**Comment by patric-eberle** [comment]
@jenda77 siehe https://github.com/verstaerker/i18nl10n/issues/88#issuecomment-143721932

**Comment by internetinnovations** [comment]
@patric-eberle 
Could you please explain this issue in detail?
