### ISSUE TITLE
Fehlermeldung beim Speichern der Seiten Lokalisierung

### ISSUE THREAD

**Issue by ghost** [exploreimpact/contao-i18nl10n#90]
Wenn ich im Root meiner seite im punkt i18nl10n-Einstellungen eine Sprache unter Seiten Lokalisierungen wähle (Englisch) und dann speichere, kommt folgende Fehlermeldung:

Fatal error: Call to undefined function Contao\hex2bin() in /usr/www/users/xxx/system/modules/core/library/Contao/StringUtil.php on line 554

Ausserdem hab ich in den Einstellungen keinen Abschnitt Mehrsprachige Inhalte (i18nl10n). Der sollte doch eigentlich da sein, nicht?

Ich habe die Contaoversion 3.5.3 und i18nl10n version 1.5.4

**Comment by ghost** [comment]
Ok, konnte den Fehler mit einem Update der PHP version beheben. 

Habe aber noch immer keine Einstellungen, so wie in der Doku beschrieben: https://github.com/verstaerker/i18nl10n/wiki/v1_settings_de

**Comment by patric-eberle** [comment]
Hallo Fabian
Das Wiki wartet leider immer noch sehnsüchtig auf ein Update. Die Sprachen werden neu über die Root-Seite eines Seitenbaums definiert. Die Optionen für die Ausgabe der URL findest du im Abschnitt Frontend-Einstellungen in den Einstellungen.

**Comment by ghost** [comment]
Ok danke!
Und wie kann ich nun Übersetzungen anlegen? Ich habe unter "Mehrsprachige Seiten" eine "Neue L10N" angelegt.
Ich habe ein neues Frontend-Modul des Typs "Sprachwahl" angelegt und in mein Layout eingebunden. Es wird allerdings nichts angezeigt.
Gibt es irgendwo eine Anleitung zur neuesten Version oder kannst du mir so vielleicht unter die Arme greifen, Patric Eberle?
Muchisimas gracias

**Comment by patric-eberle** [comment]
1. Im Startpunkt eines Seitenbaumes (Seitenstruktur) unter i18nl10n-Einstellungen zusätzliche Sprachen für diesen Baum definieren.
2. Unter Mehrsprachige Seiten L10N Kopien deiner Hauptsprach-Seiten anlegen.
3. Inhalte erfassen.

Die Sprachwahl im FE wird nur angezeigt, wenn für eine Seite auch alternative Sprachen zur Verfügung stehen.

**Comment by ghost** [comment]
Danke. Punkt 1 + 2 hab ich gemacht.
Meine Standardsprache ist deutsch, ich habe nun zusätzlich eine Englische L10N angelegt.

Punkt 3 ist mir nicht klar. Wie und wo kann ich den jetzt die tatsächliche Übersetzung machen?

**Comment by ghost** [comment]
OK, das ist eh im Wiki beschrieben: https://github.com/verstaerker/i18nl10n/wiki/v1_content_de

danke für die hilfe!

**Comment by ghost** [comment]
Ok, eine Frage hab ich noch, wie kann ich Frontend-Module übersetzen?
Ich hab zB eine Navigation, die die Seitentitel als navigationselemente rendert. Diese werden aber immer nur in der Standardsprache angezeigt, obwohl ich die Seitentitel in der übersetzung angepasst habe.

**Comment by patric-eberle** [comment]
Bei Modulen sind meistens mehrere Varianten nötig. Das kommt allerdings auf das Modul an. Bei Modulen die direkt auf die Seitenstruktur von Contao zugreiffen (was bei deinem der Fall sein könnte) kann ich leider nicht garantieren das es eine Möglichkeit gibt sie in Kombination mit i18nl10n zu verwenden. An dieser Stelle kann ich dir leider nicht weiter helfen.

**Comment by ghost** [comment]
das heißt ich hätte gleich besser einen kompletten zweiten seitenbaum anlegen sollen??

**Comment by ghost** [comment]
kann ich im template der navigation abhängig vom query parameter die übersetzung des seitentitels auslesen und anzeigen?

**Comment by patric-eberle** [comment]
Ich verstehe leider immer noch nicht, was genau das Problem ist. Wenn du den Titel der aktuellen Seite ausgeben möchtest kannst du einfach den inserttag {{page::title}} an der entsprechenden Stelle einfügen. Falls du aktuell versuchst {{link::##}} zu verwenden, da gibt es noch einen Bug (#87). Oder du schaust dir mal die vom Modul gelieferten Templates an, die eine eigene Funktion zum erstellen der Navigationslinks aufruft.

**Comment by ghost** [comment]
Was ich möchte, ist ganz einfach. Ich habe ein Frontendmodul "Navigationsmenü" eingebunden. Dort hab ich ein paar Seiten eingebunden. Das Template für das Navigationsmenü sieht vereinfacht so aus:

```
<ul>
  <?php foreach ($this->items as $key=>$item): ?>
      <li>
        <a href="<?php echo $item['href']; ?>">
          <?php echo $item['link']; ?>
        </a>
        <?php echo $item['subitems']; ?>
      </li>
  <?php endforeach; ?>
</ul>
```

Dadurch wird aber nur der Titel der Seite ausgegeben, und der ist auf Deutsch. Wenn ich allerdings im Frontend die Übersetzung nach Englisch aktiviere (?language=en) dann wird nicht der englische, übersetzte Titel angezeigt, weil ja das Template nichts davon weiß.

Alles was ich möchte ist, das auch im Menü die Übersetzungen funktionieren.

**Comment by patric-eberle** [comment]
Bei der Verwendung des Core-Modules sollte eines der mitgelieferten i18nl10n Templates verwendet werden, die im Modul zur Verfügung stehen. Dann stimmen auch die Titel. Falls du selber noch Code anpassen willst, solltest du ebenfalls diese Templates als Basis nehmen.

**Comment by internetinnovations** [comment]
This ticket will be closed, as it does not concern any issues with the extension itself.
