### ISSUE TITLE
Fehler: Kein automatischer Wechsel zu der Hauptsprache

### ISSUE THREAD

**Issue by jankout** [exploreimpact/contao-i18nl10n#92]
Hallo Patric,

leider funktioniert der automatische Wechsel zu der Hauptsprache nicht. Wenn ich mir die Seite auf meinen Handy anschaue, wo Tschechisch als Hauptsprache eingestellt ist, müsste ich eigentlich die englische Variante der Webseite angezeigt bekommen. Allerdings passiert es nicht, sondern es wird die zuletzt besuchte Sprachvariante angezeigt.

**Comment by internetinnovations** [comment]
@jankout This problem needs to be reproduced, as the current i10nl10n does not have any language related cookies, nor does it detect the client language to manage automatic redirects.
This issue might be closed without further investigation.
