### ISSUE TITLE
Keine automatische Alias Generierung der Lokalisierung

### ISSUE THREAD

**Issue by neckarpixel** [exploreimpact/contao-i18nl10n#94]
Hallo,
erstmal danke für das Plugin, echt super.

Ich bin gerade dabei, meine deutsche Seite Schritt für Schritt zu übersetzen.
Beim Anlegen der englischen Seiten unter "Mehrsprachige Seiten" lege ich eine neue L10N an,
vergebe den englischen Titel und klicke auf speichern.
Allerdings wird dann der Alias aus dem deutschen Seitenbaum generiert und nicht vom englischen.
Mache ich irgendwas falsch oder muss man jeden Alias manuell anlegen?

Grüße

**Comment by pcr-coding** [comment]
Wird die Seite unter `Seitenstruktur` in deutsch angelegt, so wird automatisch eine englische Seite (mit deutschem Titel und Alias)  unter `Mehrsprachige Seiten` angelegt. Diese kann jetzt über `Mehrsprachige Seiten` geändert werden. Dort gibt man den englischen Titel ein und löscht den Alias einfach komplett raus. Mit `Speichern` oder `Speichern und Schließen` wird dann automatisch ein neuer Alias aus dem englischen Titel erzeugt.

Funktioniert bei mir zumindestens so ganz gut.

**Comment by internetinnovations** [comment]
The current behavior (mentioned by pcr-coding) is working. This ticket will be closed. If there are any suggestions how to optimize this function, please create a new issue.
