### ISSUE TITLE
Wik: Konfiguration für Contao 3 aktualisieren

### ISSUE THREAD

**Issue by rolandschuetz** [exploreimpact/contao-i18nl10n#95]
Hallo,

erstmals danke für die SUPER Erweiterung! Ich werd die Erweiterung ab jetzt öfters verwenden und hoffentlich auch bissl helfen können.

Ich glaube beider Contao 3 Konfiguration sit ein Fehelr, war mir aber nicht 100% sicher und habs daher nicht gleich selbst geändert.
Die Konfiguration der Sprachen findet in der Root-Seite (via Seitenstruktuer) und nicht in den Einstellungen statt!?

Lg,
Roland

**Comment by internetinnovations** [comment]
This is a small mistake inside the wiki. The documentation (wiki & readme) will be updated.
This will not happen with the next release.
