### ISSUE TITLE
Undefinierte Sprachen unterstützt

### ISSUE THREAD

**Issue by rolandschuetz** [exploreimpact/contao-i18nl10n#96]
Hallo!

Wenn ich meine Seite für die Sprachen en und de konfiguriere werden die Seiten /de/unterseite.html und /en/unterseite.html erstellt. Super.
Die Seite /es/unterseite.html funktioniert aber genauso, und ist somit ein direktes Duplikat. Das ist leider ein wirkliches Problem und birgt das Risiko die Google-Suche komplett kaputt zu machen.

Ein weiteres Problem ist, wenn ich nun sprachabhängig Inhalte anzeige sieht die Website sogar echt kaputt aus.

**Comment by internetinnovations** [comment]
This is a general Contao issue. We will dig into this. This won't be solved in the next release.
