### ISSUE TITLE
Doppelte Startseiten URL

### ISSUE THREAD

**Issue by kimilau** [exploreimpact/contao-i18nl10n#97]
Momentan ist die Startseite unter der http://BasisURL.eu sowie http://BasisURL.eu/de/index erreichbar.
Das gleiche Problem habe ich auch bei der englischen Übersetzung.

Eigentlich hätte ich gerne als Startseite http://BasisURL.eu/de sowie http://BasisURL.eu/en

**Comment by jankout** [comment]
Ich bin auch dafür, dass man das wie bei dem Contaostandard hat: nur einmal, und zwar de/ für die Startseite, damit man gleich weiß, dass man die deutsche (oder wie auch immer) zur Ansicht bekommt.

**Comment by internetinnovations** [comment]
We will evaluate a solution for this issue. This task will not be realized in the next version.
To solve this issue temporarily, you can add a rule to the htaccess file.
