### ISSUE TITLE
sitemap.xml - please respect "Show in sitemap" and "Do not search" 

### ISSUE THREAD

**Issue by internethering** [exploreimpact/contao-i18nl10n#99]
I've some pages with the setting "Show in sitemap": "show never" and/or enabled "Do not search". i18nl10n ignore this settings and show the translated urls not in the sitemap.xml and do not perform indexing for search.

translated 404-pages should not be indexed too like contao behavior

**Comment by jankout** [comment]
:+1:

**Comment by internetinnovations** [comment]
Most probably we will integrate our new sitemap extension into the i18nl10n. That might also solve this 404 pages and "Show in sitemap" / "show never"  indexing issue.

The "Do not search" function needs to be solved with the refactoring of the search feature compatibility in general.
